import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import PokemonCard from "../pages/pokemonCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [pokemon, setPokemon] = useState([]);
  const [textInput, setTextInput] = useState("");
  const [filteredPokemon, setFilteredPokemon] = useState([]);

  const fetchData = () => {
    fetch(`https://pokeapi.co/api/v2/pokemon?limit=2000`)
      .then((res) => res.json())
      .then((data) => {
        setPokemon(data.results);
        setFilteredPokemon(data.results);
      });
  };

  useEffect(fetchData, []);
  console.log(pokemon[1]);

  const handleChange = (e) => {
    setTextInput(e.target.value);
  };

  // useEffect(() => {
  //   if (textInput) {
  //     // const filtered = filteredPokemon.filter((_pokemon) => {
  //     //   // return pokemon.strMeal.toLowerCase().includes(textInput.toLowerCase());
  //     // });
  //   //   setFilteredPokemon(filtered);
  //   // } else {
  //   //   setFilteredPokemon(pokemon);
  //   // }
  // }, [textInput]);

  return (
    <>
      <Head>
        <title>Martins Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>HEJ</h1>

        <div className="searchBar">
          <input
            type="text"
            placeholder="Search Pokemon"
            onChange={handleChange}
          />
        </div>
      </main>
    </>
  );
}
