import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import PokemonCard from "../pages/pokemonCard";

export default function Home() {
  const [pokemon, setPokemon] = useState([]);
  const [textInput, setTextInput] = useState("");
  const [filteredPokemon, setFilteredPokemon] = useState([]);

  const fetchData = () => {
    fetch(`https://pokeapi.co/api/v2/pokemon?limit=493`)
      .then((res) => res.json())
      .then((data) => {
        setPokemon(data.results);
        setFilteredPokemon(data.results);
      });
  };

  useEffect(fetchData, []);

  const handleChange = (e) => {
    setTextInput(e.target.value);
  };

  useEffect(() => {
    if (textInput) {
      const filtered = filteredPokemon.filter((_pokemon) => {
        return _pokemon.name.toLowerCase().includes(textInput.toLowerCase());
      });
      setFilteredPokemon(filtered);
    } else {
      setFilteredPokemon(pokemon);
    }
  }, [textInput]);

  return (
    <>
      <Head>
        <title>Martins Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="searchBar">
        <input
          type="text"
          placeholder="Search Pokemon"
          onChange={handleChange}
        />
      </div>
      <main className="wrapper">
        {/* <PokemonCard name={pokemon[1].name} url={pokemon[1].url} /> */}
        {filteredPokemon.length &&
          filteredPokemon.map((_pokemon, index) => {
            return (
              <PokemonCard key={index} name={_pokemon.name} url={_pokemon.url}>
                {_pokemon.name}
              </PokemonCard>
            );
          })}
      </main>
    </>
  );
}
