import Head from "next/head";
import { useEffect, useState } from "react";
import SpaceCard from "./SpaceCard";

export default function Home() {
  const [launches, setLaunches] = useState([]);
  const [textInput, setTextInput] = useState("");
  const [filteredLaunches, setFilteredLaunches] = useState([]);

  const fetchData = () => {
    fetch(`https://api.spacexdata.com/v5/launches/`)
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setLaunches(data);
        setFilteredLaunches(data);
      });
  };

  useEffect(fetchData, []);

  const handleChange = (e) => {
    setTextInput(e.target.value);
  };

  useEffect(() => {
    if (textInput) {
      const filtered = filteredLaunches.filter((_launches) => {
        return _launches.name.toLowerCase().includes(textInput.toLowerCase());
      });
      setFilteredLaunches(filtered);
    } else {
      setFilteredLaunches(launches);
    }
  }, [textInput]);

  return (
    <>
      <Head>
        <title>Martins Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="searchBar">
        <input
          type="text"
          placeholder="Search Launches"
          onChange={handleChange}
        />
      </div>
      <main className="wrapper">
        {filteredLaunches.length &&
          filteredLaunches.map((_launches, index) => {
            return (
              <SpaceCard
                key={index}
                name={_launches.name}
                source={_launches.links.patch.small}
                date={_launches.date_local}
                detail={_launches.details}
                id={_launches.flight_number}
              />
            );
          })}
      </main>
    </>
  );
}
